
package org2.java.identity.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TokenController", targetNamespace = "http://webservice.identity.java.org2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TokenController {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateToken", targetNamespace = "http://webservice.identity.java.org2/", className = "org2.java.identity.webservice.ValidateToken")
    @ResponseWrapper(localName = "validateTokenResponse", targetNamespace = "http://webservice.identity.java.org2/", className = "org2.java.identity.webservice.ValidateTokenResponse")
    @Action(input = "http://webservice.identity.java.org2/TokenController/validateTokenRequest", output = "http://webservice.identity.java.org2/TokenController/validateTokenResponse")
    public int validateToken(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
